// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/pdefs/hello.proto

package pdefs // import "github.com/s4kibs4mi/awesome-twirp/protobuf/pdefs"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hello struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_361033b26d780f73, []int{0}
}
func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (dst *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(dst, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Hello) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Hello)(nil), "pdefs.Hello")
}

func init() { proto.RegisterFile("protobuf/pdefs/hello.proto", fileDescriptor_hello_361033b26d780f73) }

var fileDescriptor_hello_361033b26d780f73 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x48, 0x49, 0x4d, 0x2b, 0xd6, 0xcf, 0x48, 0xcd, 0xc9, 0xc9,
	0xd7, 0x03, 0x0b, 0x0a, 0xb1, 0x82, 0x85, 0x94, 0x2c, 0xb9, 0x58, 0x3d, 0x40, 0xa2, 0x42, 0x62,
	0x5c, 0x6c, 0xa1, 0xc5, 0xa9, 0x45, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50,
	0x9e, 0x90, 0x04, 0x17, 0xbb, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x04, 0x13, 0x58, 0x02,
	0xc6, 0x75, 0x32, 0x8e, 0x32, 0x4c, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5,
	0x2f, 0x36, 0xc9, 0xce, 0x4c, 0x2a, 0x36, 0xc9, 0xcd, 0xd4, 0x4f, 0x2c, 0x4f, 0x2d, 0xce, 0xcf,
	0x4d, 0xd5, 0x2d, 0x29, 0xcf, 0x2c, 0x2a, 0xd0, 0x47, 0x75, 0x42, 0x12, 0x1b, 0x98, 0x6f, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x91, 0x89, 0x93, 0x4b, 0x9b, 0x00, 0x00, 0x00,
}
