// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/pdefs/service.proto

package pdefs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqHello struct {
	Hello                *Hello   `protobuf:"bytes,1,opt,name=Hello" json:"Hello,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHello) Reset()         { *m = ReqHello{} }
func (m *ReqHello) String() string { return proto.CompactTextString(m) }
func (*ReqHello) ProtoMessage()    {}
func (*ReqHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_43e7e2530e65f074, []int{0}
}
func (m *ReqHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHello.Unmarshal(m, b)
}
func (m *ReqHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHello.Marshal(b, m, deterministic)
}
func (dst *ReqHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHello.Merge(dst, src)
}
func (m *ReqHello) XXX_Size() int {
	return xxx_messageInfo_ReqHello.Size(m)
}
func (m *ReqHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHello.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHello proto.InternalMessageInfo

func (m *ReqHello) GetHello() *Hello {
	if m != nil {
		return m.Hello
	}
	return nil
}

type ResHello struct {
	GoodBye              *GoodBye `protobuf:"bytes,1,opt,name=GoodBye" json:"GoodBye,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResHello) Reset()         { *m = ResHello{} }
func (m *ResHello) String() string { return proto.CompactTextString(m) }
func (*ResHello) ProtoMessage()    {}
func (*ResHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_43e7e2530e65f074, []int{1}
}
func (m *ResHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHello.Unmarshal(m, b)
}
func (m *ResHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHello.Marshal(b, m, deterministic)
}
func (dst *ResHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHello.Merge(dst, src)
}
func (m *ResHello) XXX_Size() int {
	return xxx_messageInfo_ResHello.Size(m)
}
func (m *ResHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHello.DiscardUnknown(m)
}

var xxx_messageInfo_ResHello proto.InternalMessageInfo

func (m *ResHello) GetGoodBye() *GoodBye {
	if m != nil {
		return m.GoodBye
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqHello)(nil), "pdefs.ReqHello")
	proto.RegisterType((*ResHello)(nil), "pdefs.ResHello")
}

func init() {
	proto.RegisterFile("protobuf/pdefs/service.proto", fileDescriptor_service_43e7e2530e65f074)
}

var fileDescriptor_service_43e7e2530e65f074 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x48, 0x49, 0x4d, 0x2b, 0xd6, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb,
	0x4c, 0x4e, 0xd5, 0x03, 0x0b, 0x0b, 0xb1, 0x82, 0x05, 0xa5, 0xa4, 0xd0, 0x14, 0x65, 0xa4, 0xe6,
	0xe4, 0xe4, 0x43, 0x94, 0x48, 0x49, 0xa0, 0xc9, 0x25, 0x55, 0x42, 0x35, 0x2b, 0xe9, 0x71, 0x71,
	0x04, 0xa5, 0x16, 0x7a, 0x80, 0xd4, 0x0a, 0x29, 0x71, 0xb1, 0x82, 0x19, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xdc, 0x46, 0x3c, 0x7a, 0x60, 0xc5, 0x7a, 0x60, 0xb1, 0x20, 0x88, 0x94, 0x92, 0x09, 0x48,
	0x7d, 0x31, 0x44, 0xbd, 0x06, 0x17, 0xbb, 0x7b, 0x7e, 0x7e, 0x8a, 0x53, 0x65, 0x2a, 0x54, 0x07,
	0x1f, 0x54, 0x07, 0x54, 0x34, 0x08, 0x26, 0x6d, 0xe4, 0xcc, 0x25, 0xec, 0x58, 0x9e, 0x5a, 0x9c,
	0x9f, 0x9b, 0x1a, 0x52, 0x9e, 0x59, 0x54, 0x10, 0x0c, 0x71, 0xbf, 0x90, 0x0e, 0x17, 0x47, 0x70,
	0x62, 0x25, 0xc4, 0x30, 0x7e, 0xa8, 0x5e, 0x98, 0x6b, 0xa4, 0x10, 0x02, 0x10, 0xeb, 0x9c, 0xd8,
	0xa3, 0x20, 0x3e, 0x4d, 0x62, 0x03, 0x3b, 0xdd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x9f,
	0xab, 0xa4, 0x17, 0x01, 0x00, 0x00,
}
